### ISSUE TITLE
Non-Windows github actions checks fail

### ISSUE THREAD

**Issue by pepijn-devries** [pepijn-devries/openmpt#7]
This is because dependencies `libopenmpt` and `portaudio` are not available.

**Comment by pepijn-devries** [comment]
Submitted fixed pull request:
https://github.com/rstudio/r-system-requirements/pull/193

**Comment by pepijn-devries** [comment]
Builds and checks on all operating systems now seem to work. @jeroen Thanks for you contributions and suggestions! I would appreciate it if you could give the configure script a glance if it seems OK to you.

**Comment by pepijn-devries** [comment]
Fixed in https://github.com/pepijn-devries/openmpt/commit/666ba018902ab0958989b1d8c2b6d95b408d10a1

**Comment by jeroen** [comment]
I wouldn't worry too much about wasm, that's very experimental stuff, and it would require building all of your dependency libs for wasm, which is a whole other business.

Don't forget to add to your readme that users can install binaries for win/mac from https://pepijn-devries.r-universe.dev/openmpt so they don't have to compile things ;)

**Comment by pepijn-devries** [comment]
Readme is updated with https://github.com/pepijn-devries/openmpt/pull/15
